# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provider "libvirt" do |vb|
     vb.memory = "2048"
     vb.cpus = 2
  end

  NodeCount = 4

  (1..NodeCount).each do |i|
    config.vm.define "mysql-#{i}" do |conf|
      conf.vm.box = "generic/ubuntu2004"
      conf.vm.hostname = "mysql-#{i}.local"
      conf.vm.provision "shell", path: "scripts/Ubuntu/bootstrap.sh"
    end 
  end

end