# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # config.vm.provider "virtualbox" do |vb|
  config.vm.provider "libvirt" do |vb|
    #  vb.gui = false
     vb.memory = "2048"
     vb.cpus = 2
  end

  # 
  config.vm.define "mysql-1" do |conf|
    conf.vm.box = "generic/ubuntu2004"
    conf.vm.hostname = 'mysql-1.local'
    # conf.vm.network "private_network", ip: "192.168.22.10"
    conf.vm.provision "shell", path: "scripts/Ubuntu/bootstrap.sh"
    # conf.vm.provision "shell", path: "scripts/install-mysql.sh"
  end 

  # 
  config.vm.define "mysql-2" do |conf|
    conf.vm.box = "generic/ubuntu2004"
    conf.vm.hostname = 'mysql-2.local'
    # conf.vm.network "private_network", ip: "192.168.22.11"
    conf.vm.provision "shell", path: "scripts/Ubuntu/bootstrap.sh"
    # conf.vm.provision "shell", path: "scripts/install-mysql.sh"
  end

end